version: "3"

volumes:
  inventory_local_postgres_data: {}
  inventory_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: inventory_local_django
    container_name: inventory_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: inventory_production_postgres
    container_name: inventory_local_postgres
    volumes:
      - inventory_local_postgres_data:/var/lib/postgresql/data:Z
      - inventory_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  # docs:
  #   image: inventory_local_docs
  #   container_name: inventory_local_docs
  #   platform: linux/x86_64
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/docs/Dockerfile
  #   env_file:
  #     - ./.envs/.local/.django
  #   volumes:
  #     - ./docs:/docs:z
  #     - ./config:/app/config:z
  #     - ./inventory:/app/inventory:z
  #   ports:
  #     - "9000:9000"
  #   command: /start-docs

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: inventory_local_mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: inventory_local_redis

  celeryworker:
    <<: *django
    image: inventory_local_celeryworker
    container_name: inventory_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: inventory_local_celerybeat
    container_name: inventory_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: inventory_local_flower
    container_name: inventory_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
