# Generated by Django 3.2.15 on 2022-12-05 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCircular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('job_responsibilities', models.TextField()),
                ('job_requirements', models.TextField()),
                ('job_location', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('FULL_TIME_REMOTE', 'Full time remote'), ('PART_TIME_REMOTE', 'Part time remote'), ('CONTRACTUAL', 'Contractual'), ('TEMPORARY', 'Temporary'), ('INTERNSHIP', 'Internship')], max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished')], default='UNPUBLISHED', max_length=255)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.company')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.department')),
                ('job_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.jobposition')),
            ],
            options={
                'verbose_name': 'Job Circular',
                'verbose_name_plural': 'Job Circulars',
            },
        ),
    ]
