# Generated by Django 3.2.15 on 2022-12-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_jobcircular'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='github_profile',
            field=models.URLField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='linked_in_profile',
            field=models.URLField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DECLINED', 'Declined'), ('INTERVIEW', 'Interview'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=255),
        ),
    ]
