# Generated by Django 3.2.15 on 2022-12-05 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_auto_20221205_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='linked_in_profile',
            new_name='linkedin_profile',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='career_objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='circular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.jobcircular'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.jobposition'),
        ),
    ]
