# Generated by Django 3.2.15 on 2022-12-05 17:40

from django.db import migrations, models
import django.db.models.deletion
import inventory.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_auto_20221205_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='employee/resume/', validators=[inventory.common.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(null=True, upload_to='application/resume/', validators=[inventory.common.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='jobcircular',
            name='job_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('FULL_TIME_REMOTE', 'Full Time Remote'), ('PART_TIME_REMOTE', 'Part Time Remote'), ('CONTRACTUAL', 'Contractual'), ('TEMPORARY', 'Temporary'), ('INTERNSHIP', 'Internship')], max_length=255),
        ),
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee'),
        ),
    ]
