# Generated by Django 3.2.15 on 2023-01-06 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_auto_20221205_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[0-9-+ ]+$', "Phone number must be entered in the format: '+9999-99999'. Up to 15 digits allowed."), django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[0-9-+ ]+$', "Phone number must be entered in the format: '+9999-99999'. Up to 15 digits allowed."), django.core.validators.MinLengthValidator(11)]),
        ),
    ]
