---

# Virtualenv settings.
recreate_virtualenv: true
virtualenv_python_version: "{{ base_python_package }}"

# Application settings.
virtualenv_path: "{{ ansistrano_deploy_to }}/{{ ansistrano_current_dir }}/venv"
backend_project_path: "{{ ansistrano_deploy_to }}/{{ ansistrano_current_dir }}"
application_log_dir: "{{ virtualenv_path }}/logs"
application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"
requirements_file: "{{ backend_project_path }}/requirements/production.txt"
pip_use_upgrade_flag: false


# Gunicorn settings.
gunicorn_user: "{{ ansible_user }}"
gunicorn_group: www-data
gunicorn_num_workers: 4
gunicorn_max_requests: 0
gunicorn_timeout_seconds: 300

# Nginx settings.
nginx_static_dir: "{{ backend_project_path }}/staticfiles/"
nginx_media_dir: "{{ backend_project_path }}/{{ backend_project_name }}/media/"

# Application settings.
django_username: "devxhub"
django_email: "eliyas@devxhub.com"
django_password: "JE86vlSE4xLGIJNDGd66LoAvdfNzvJV7rzUvjik3"
django_settings_file: "config.settings.production"
django_secret_key: "akr2icmg1n8%z^3fe3c+)5d0(t^cy-2_25rrl35a7@!scna^1#"
run_django_db_migrations: true
run_django_collectstatic: true
run_django_user: false
sendgrid_api_key: "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"
sendgrid_generate_message_id: True
sendgrid_merge_field_format: None
sentry_dsn: "https://04117a6e459b4b378819457719ee9e08@o4504152481005568.ingest.sentry.io/4504152483168256"

# Django environment variables.
django_environment:
  DJANGO_READ_DOT_ENV_FILE: True
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SUPERUSER_PASSWORD: "{{ django_password }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  DJANGO_ALLOWED_HOSTS: "{{ backend_server_name }}, {{ frontend_server_name }}"
  DJANGO_ADMIN_URL: "admin/"
  DJANGO_DEFAULT_FROM_EMAIL: "DevXHub <admin@devxhub.com>"
  DJANGO_DEBUG: False
  DB_HOST: 127.0.0.1
  DB_PORT: 5432
  DB_NAME: "{{ db_name }}"
  DB_USER: "{{ db_user }}"
  DB_PASSWORD: "{{ db_password }}"
  DATABASE_URL: "postgres://{{ db_password }}:{{ db_user }}@127.0.0.1:5432/{{ db_name }}"
  REDIS_URL: "redis://{{ redis_requirepass }}@{{ redis_bind_interface }}:{{ redis_port }}/0"
  CELERY_BROKER_URL: "redis://{{ redis_requirepass }}@{{ redis_bind_interface }}:{{ redis_port }}/0"
  MEDIA_ROOT: "{{ nginx_media_dir }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  SENDGRID_API_KEY: "{{ sendgrid_api_key }}"
  SENDGRID_GENERATE_MESSAGE_ID: "{{ sendgrid_generate_message_id }}"
  SENDGRID_MERGE_FIELD_FORMAT: "{{ sendgrid_merge_field_format }}"
  SENTRY_DSN: "{{ sentry_dsn }}"
