# Generated by Django 3.2.15 on 2023-01-06 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('^[0-9-+ ]+$', "Phone number must be entered in the format: '+9999-99999'. Up to 15 digits allowed."), django.core.validators.MinLengthValidator(11)]),
        ),
    ]
