# Generated by Django 3.2.15 on 2022-12-04 10:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(blank=True, choices=[('ART, PHOTOGRAPHY & CREATIVE SERVICES', 'Art, Photography & Creative Services'), ('CONSTRUCTION & HOME IMPROVEMENT', 'Construction & Home Improvement'), ('CONSULTING & PROFESSIONAL SERVICES', 'Consulting & Professional Services'), ('FINANCIAL SERVICES & INSURANCE', 'Financial Services & Insurance'), ('HAIR, SPA & AESTHETICS', 'Hair, Spa & Aesthetics'), ('NON-PROFITS, ASSOCIATIONS & GROUPS', 'Non-profits, Associations & Groups'), ('REAL ESTATE', 'Real Estate'), ('RETAILERS, RESELLERS & SALES', 'Retailers, Resellers & Sales'), ('WEB, TECH & MEDIA', 'Web, Tech & Media'), ('OTHER: I MAKE OR SELL A PRODUCT', 'Other: I make or sell a PRODUCT'), ('OTHER: I PROVIDE A SERVICE', 'Other: I provide a SERVICE')], max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Company Type',
                'verbose_name_plural': 'Company Types',
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Company User',
                'verbose_name_plural': 'Company Users',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('$', '$ Dollars'), ('৳', '৳ Bangladesh Taka')], max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z-,-.-_ ]+$', 'Only alphanumeric characters are allowed.')])),
                ('last_name', models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z-,-.-_ ]+$', 'Only alphanumeric characters are allowed.')])),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.RegexValidator(message="Email must be entered in the format: 'yourmail@gamil.com' ", regex='^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')])),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('INVESTOR', 'Investor'), ('BORROWER', 'Borrower')], max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Customer Type',
                'verbose_name_plural': 'Customer Types',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('EN', 'English'), ('BN', 'Bengali')], max_length=50, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='languages/')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.language')),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
