# Generated by Django 3.2.15 on 2022-12-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(choices=[('USD', '$ U.S. Dollar'), ('BDT', '৳ Bangladesh Taka')], max_length=50, null=True, unique=True),
        ),
    ]
