# Generated by Django 3.2.15 on 2022-12-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20221228_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(choices=[('USD', 'USD'), ('BDT', 'USD')], max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('EN', 'EN'), ('BD', 'BD')], max_length=50, null=True, unique=True),
        ),
    ]
