# Generated by Django 3.2.15 on 2023-01-06 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_faq_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(choices=[('USD', 'USD'), ('BDT', 'BDT')], max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z-,-.-_ ]+$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[0-9-+ ]+$', "Phone number must be entered in the format: '+9999-99999'. Up to 15 digits allowed."), django.core.validators.MinLengthValidator(11)]),
        ),
    ]
