# Generated by Django 3.2.15 on 2022-12-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(blank=True, default='Piece', max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('account_type', models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income'), ('DUE_PAY', 'Due Pay'), ('DUE_RECEIVE', 'Due Receive'), ('INVEST', 'Invest'), ('PAYROLL', 'Payroll')], max_length=50, null=True)),
                ('income_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('due', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cash_in_hand', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_receivable', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
    ]
