# Generated by Django 3.2.15 on 2022-12-05 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.company'),
        ),
    ]
