# Generated by Django 3.2.15 on 2022-12-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_chartofaccount_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account_type',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income'), ('Due Pay', 'Due Pay'), ('Due Receive', 'Due Receive'), ('Invest', 'Invest'), ('Payroll', 'Payroll')], max_length=50, null=True),
        ),
    ]
