# Generated by Django 3.2.15 on 2022-12-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_transaction_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('Piece', 'Piece'), ('Kg', 'Kg'), ('Gram', 'Gram'), ('Litre', 'Litre'), ('Box', 'Box'), ('Pound', 'Pound'), ('Dozen', 'Dozen'), ('Other', 'Other')], help_text='Unit of the product', max_length=50, null=True),
        ),
    ]
