# Generated by Django 3.2.15 on 2022-12-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
