# Generated by Django 3.2.15 on 2023-01-16 12:14

from django.db import migrations, models
import inventory.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, validators=[inventory.common.validators.paid_amount_validator]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[inventory.common.validators.quantity_validator]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, validators=[inventory.common.validators.unit_price_validator]),
        ),
    ]
